### ISSUE TITLE
Change CI/CD approach to use scripts

### ISSUE THREAD

**Issue by malak-coforma** [coforma-acme/acme-tech-challenge#72]
## Description

We're not able to use Github action running to set up our EC2 instance.

## Requirements

- [ ] install & configure script
- [ ] compile & deploy script
- [ ] run tests script
- [ ] uninstall script -- duplicate on #51 

## Next Steps

- [ ] update `README` items:
  - [ ] #18 (install and configure script)
  - [ ] #22 (compile and deploy script)
  - [ ] #23 (run tests script)
  - [ ] #24 (uninstall script)

## Tech Notes

From the second amended Q&A items:

> Q: Answers to the questions add a new requirement, “The Quoter’s scripts should install the tools and libraries needed to run the install, test, and uninstall scripts.” We previously thought that tools like Docker and Terraform would already be included in the government’s EC2 instance, as they are technologies that are part of the challenge.
> Our team already started our sprint based on the information previously provided. We now have less than a day to incorporate the new requirements and complete our sprint. Can the government allow some flexibility in the sprint length?
> 
> A: The Government will provide an additional day for the sprint period in order to incorporate answers provided to Phase 3 questions. As a result, the sprint may be a 9-calendar day period and Phase 3 responses are now due on August 15, 2022 3 PM EDT.
